### ISSUE TITLE
Commit Artifacts Directory

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/contracts-v2#11]
Since the contracts are getting close to being frozen, it would be useful if the `artifacts` directory is committed so that a consumer of this gitrepo doesn't need `yarn` and have to install a bunch of dependencies to get the compiled contracts/abi. This is useful for the script I'm writing to autogenerate bindings to the contracts, I'd like to download the artifact JSON files directly from github and then use the abi and bytecode directly with `abigen`.

What do you think?

**Comment by tynes** [comment]
@karlfloersch had the idea of having the CI push the commits with the artifacts directories. It would have to do a diff before the commit, otherwise there would be an additional commit each time there was a push to master by the CI even if the contracts didn't change. I think the npm package would want the artifacts as well, so the publish step would have to be done by the CI after the commit or locally after the commit by the CI

**Comment by kfichter** [comment]
Closing old issues, this one has been solved
