### ISSUE TITLE
Rename Canonical Tx Chain -> Tx Chain & State Commitment Chain -> State Chain

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/contracts-v2#45]
**Is your feature request related to a problem? Please describe.**
It is really annoying saying "Canonical Tx Chain" or "State Commitment Chain" -- shorter is better.

**Describe the solution you'd like**
Rename Canonical Tx Chain -> Tx Chain & State Commitment Chain -> State Chain

**Comment by kfichter** [comment]
Closing old issues, we're way past this one 😆
