### ISSUE TITLE
Remove `Proxy__` prefix

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/contracts-v2#55]
**Describe the bug**
Right now all deployed contracts in our deployment object are prefixed with `Proxy__`. This is old behavior when we were auto-generating proxies for all contracts, but now it's really unneeded.

**Steps to reproduce**
Deploy some contracts and look at the output object.

**Expected behavior**
Just provide the contract name with no `Proxy__`, or re-add a proxy system.

**Comment by kfichter** [comment]
@karlfloersch is this still an issue?

**Comment by karlfloersch** [comment]
@kfichter Don't think so! Closing
