### ISSUE TITLE
Fresh `yarn add` doesn't work

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/contracts-v2#95]
**Describe the bug**

It results in a `Error: Cannot find module 'ganache-core'`

**Expected behavior**
It should just work when installing from npm

**Screenshots**

**Specifications**
 - Version:
 - OS:
 - Node Version:

**Additional context**

**Comment by kfichter** [comment]
@tynes bumping, still an issue?

**Comment by tynes** [comment]
It is still an issue and can be reproduced by:

```bash
$ yarn init -y
$ yarn add @eth-optimism/contracts
$ node -e 'require("@eth-optimism/contracts")'
```

**Comment by tynes** [comment]
It looks like `ganache-core` is in the `devDependencies` when it should be in the `dependencies`
